[DRAFT] loading .dev.vars support for pages
cloudflare/wrangler2 pull request #1274
Opened 2022-06-15 20:18 UTC by Maximo-Guk

#898

2022-06-16 11:37 UTC, threepointone commented on packages/wrangler/src/pages.tsx
> +function getDevVarsPath(): string {
```suggestion
function getDevVarsPath(): string | undefined {
```

2022-06-16 11:37 UTC, threepointone commented on packages/wrangler/src/pages.tsx
> +  return "";
```suggestion
```

2022-06-20 16:43 UTC, GregBrimble commented on packages/wrangler/src/pages/dev.tsx
> +    envPath: devVarsPath,
I think we should use [straight bindings](https://miniflare.dev/core/variables-secrets/#bindings) like wrangler proper does: https://github.com/cloudflare/wrangler2/blob/57cf14e718749ab43f70034e21e600692cc90727/packages/wrangler/src/index.tsx#L1164

And ideally the `getVarsForDev` function that they've created as well.

This'll mean that Miniflare doesn't need to know anything about the fs, and will possibly make running wrangler in some other workdir easier in the future.

2022-06-23 22:40 UTC, GregBrimble approved these changes

2022-06-23 23:27 UTC, GregBrimble requested changes
Looks like you've accidentally included the config stuff too

2022-06-25 11:37 UTC, GregBrimble commented on .changeset/wise-pens-shake.md
> +"pages-functions-app": patch
```suggestion
```

2022-06-25 11:37 UTC, GregBrimble approved these changes
Great stuff!

2022-06-25 20:07 UTC, merged