Added Global API Key (X-Auth-Key) support to Wrangler
cloudflare/wrangler2 pull request #1351
Opened 2022-06-24 16:02 UTC by geelen

Closes #1072 

* A user _must_ supply _both_ an Global API Key and Email for this to work.
* Can use `CLOUDFLARE_API_KEY` and `CLOUDFLARE_EMAIL` or the deprecated `CF_API_KEY` and `CF_EMAIL` keys.
* Takes precedence over `CLOUDFLARE_API_TOKEN` and oAuth.

Refactored the assumption that an `apiToken` was a string and have replaced that with an `ApiCredentials` type:

```ts
export type ApiCredentials =
  | {
      apiToken: string;
    }
  | {
      authKey: string;
      authEmail: string;
    };
```

This flowed _fairly_ easily through the code, picked up inside `addAuthorizationHeaderIfUnspecified`:

```ts
function addAuthorizationHeaderIfUnspecified(
  headers: Record<string, string>,
  auth: ApiCredentials
): void {
  if (!("Authorization" in headers)) {
    if ("apiToken" in auth) {
      headers["Authorization"] = `Bearer ${auth.apiToken}`;
    } else {
      headers["X-Auth-Key"] = auth.authKey;
      headers["X-Auth-Email"] = auth.authEmail;
    }
  }
}
```

I chose to preserve the semantics that if the code has injected a specific `Authorization` header, we should send it on rather than replacing it with the global Key/Email (since it's used for time-limited JWTs for Pages uploads)

2022-06-25 06:33 UTC, threepointone approved these changes
This looks great, thanks for adding tests too! I think we should remove the GLOBAL / Global word everywhere, but I'm going to stamp it anyway. Feel free to land it after removing Global.

2022-06-25 06:33 UTC, threepointone commented on packages/wrangler/src/__tests__/whoami.test.tsx
> +  it("should use a Global API Key in preference to an API key", async () => {
```suggestion
  it("should use a Global API Key in preference to an API token", async () => {
```

2022-06-25 06:33 UTC, threepointone commented on packages/wrangler/src/user/env-vars.ts
> +  variableName: "CLOUDFLARE_GLOBAL_API_KEY",
```suggestion
  variableName: "CLOUDFLARE_API_KEY",
```
we can remove this GLOBAL prefix everywhere!

2022-06-25 06:33 UTC, threepointone commented on packages/wrangler/src/user/env-vars.ts
> +  variableName: "CLOUDFLARE_GLOBAL_API_EMAIL",
```suggestion
  variableName: "CLOUDFLARE_API_EMAIL",
```

2022-06-25 06:33 UTC, threepointone commented on packages/wrangler/src/whoami.tsx
> +      ? "Global API Key"
```suggestion
      ? "API Key"
```

2022-06-25 07:29 UTC, threepointone requested changes
Please add a changeset!

2022-06-25 16:13 UTC, geelen commented
Happy to remove `GLOBAL`, only put it in because I'm not sure, otherwise, that the difference between a "key" and a "token" is particularly obvious to people. That and the Dash UI looks like this:

![image](https://user-images.githubusercontent.com/23264/175781874-e22165c5-31b9-42aa-98da-0ee80b978420.png)

Thoughts?

2022-06-27 07:27 UTC, threepointone commented
The other vars are basically the older ones but with CF replaced with CLOUDFLARE. Since these are usually typed out at the command line, I'd prefer them them to be shorter (honestly I like CF too, but coldfusion got there before us so we have to use CLOUDFLARE instead) 

BUT. I don't feel strongly about this! Feel free to take a call. I'll stamp this once you add a changeset tho.

2022-06-27 11:24 UTC, threepointone commented
Taking this over, will review and land. Thank you so much @geelen!

2022-06-27 11:39 UTC, threepointone approved these changes

2022-06-27 11:39 UTC, merged