Support passing routes as well as worker names to `wrangler tail`
cloudflare/wrangler2 pull request #1700
Opened 2022-08-18 11:56 UTC by penalosa

An initial stab at https://github.com/cloudflare/wrangler2/issues/492, following the approach outlined there:
> 1. Checking if the positional argument passed to wrangler tail <url | name> resembles a URL
> 1. Determining the zone ID from the URL (e.g. via [getZoneForRoute](https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/zones.ts#L29))
> 1. Calling [GET zone/:zone_id/workers/routes](https://api.cloudflare.com/#worker-routes-list-routes)
> 1. Finding the given URL in the returned routes
> 1. Using the worker name associated with that route to plug in to the existing tail infrastructure

Some notes:
- Distinguishing between a route and a worker name is done by checking for the presence of a `.` character, following confirmation that that will suffice.
- I've defined a new type for responses from the route list endpoint. I couldn't find anything similar, but I may have missed an existing type that should be used instead:
```
interface WorkerRoute {
	id: string;
	pattern: string;
	script: string;
}
```
- I've tested this on a worker in my CF account, but I'm unsure as to how to go about adding automated tests for the new functionality—some pointers here would be really helpful!

This PR covers exact route matching, whereas the linked issue asks for flexible route matching. Some thoughts on that:
- **Precedence** For instance, if two routes were defined (`www.example.com` and `*.example.com`), and the logs for `www.example.com` were requested, Wrangler would have to figure out that the worker on the `www.example.com` route would have served those requests, even though the `*.example.com` route would also match. This is obviously implemented somewhere, and so the precedence algorithm could be reimplemented in Wrangler to allow for this (maybe it's already implemented somewhere in Wrangler?)
- **Matching rules** The matching rules for worker routes are [documented](https://developers.cloudflare.com/workers/platform/routing/routes/#matching-behavior) so they could be implemented in Wrangler. This would be for e.g. `wrangler tail example.com/foo` to find a worker deployed on the `example.com/*` route. 
- **Filtering** A related concern is filtering URL patterns. Currently, the logs backend only supports filtering based on IP, header etc... and not on URL path. That filtering could either be done within Wrangler, or added as a filter to the logs backend, to make sure that e.g. `wrangler tail example.com/foo`, matching a worker deployed on the route `example.com/*`, only showed the logs from requests to `example.com/foo`, and not requests to `example.com/baz` (which would be handled by the same worker).

2022-08-18 14:50 UTC, caass requested changes
This looks really good! This will be a great feature and this implementation is on the right track. I left some comments, some super minor, some requiring a little refactoring.

Also, please put doc comments on any functions and/or types so that someone else can tell at a glance what their purpose is :)

2022-08-18 14:50 UTC, caass commented on .changeset/ninety-books-hope.md
> +Closes [#1505](https://github.com/cloudflare/wrangler2/issues/1505) by extending `wrangler tail` to allow for passing worker routes as well as worker script names.
Maybe an example? Something like "`wrangler tail example.com/*` will work if you have a worker assigned to the route example.com/*`

2022-08-18 14:50 UTC, caass commented on packages/wrangler/src/index.tsx
> +					describe: "Name of the worker, or route at which it runs",
```js
.positional("worker", {
  describe: "Name or route of the worker to tail"
```

2022-08-18 14:50 UTC, caass commented on packages/wrangler/src/index.tsx
> +					throw new Error(`Could not find zone for route ${args.name}`);
This error message should be more actionable by the user -- describe what exactly went wrong and how they can fix it.

2022-08-18 14:50 UTC, caass commented on packages/wrangler/src/index.tsx
> +				}
Maybe refactor into a `getWorkerForRoute` function?

2022-08-18 14:50 UTC, caass commented on packages/wrangler/src/index.tsx
> +				}
`routes.find(...`

2022-08-18 14:50 UTC, caass commented on packages/wrangler/src/index.tsx
> +								`Connecting to worker ${scriptName} at route ${args.name}`
does tail already say what worker we're connecting to?

2022-08-18 14:50 UTC, caass commented on packages/wrangler/src/index.tsx
> +								`Connecting to worker ${scriptName} at route ${args.name}`
Yes, but later in the process -- if the connection fails, we won't know what we're connecting to.

2022-08-18 14:50 UTC, caass commented on packages/wrangler/src/index.tsx
> +								`Connecting to worker ${scriptName} at route ${args.name}`
So maybe it's better to add a logger statement earlier in the tail lifecycle, before anything can fail?

2022-08-18 14:50 UTC, caass commented on packages/wrangler/src/index.tsx
> +					throw new Error(`No workers found on the route ${args.name}`);
Let's improve this error message by suggesting routes they might have meant.

2022-08-18 14:58 UTC, caass commented
> * **Precedence** For instance, if two routes were defined (`www.example.com` and `*.example.com`), and the logs for `www.example.com` were requested, Wrangler would have to figure out that the worker on the `www.example.com` route would have served those requests, even though the `*.example.com` route would also match. This is obviously implemented somewhere, and so the precedence algorithm could be reimplemented in Wrangler to allow for this (maybe it's already implemented somewhere in Wrangler?)

At the moment, if I understand correctly, this isn't an issue because we require an exact match on routes. But I see what you're saying.

> * **Matching rules** The matching rules for worker routes are [documented](https://developers.cloudflare.com/workers/platform/routing/routes/#matching-behavior) so they could be implemented in Wrangler. This would be for e.g. `wrangler tail example.com/foo` to find a worker deployed on the `example.com/*` route.

If this is documented, we could actually re-implement this in wrangler fairly easily, unless I'm mistaken. We should totally do this!

> * **Filtering** A related concern is filtering URL patterns. Currently, the logs backend only supports filtering based on IP, header etc... and not on URL path. That filtering could either be done within Wrangler, or added as a filter to the logs backend, to make sure that e.g. `wrangler tail example.com/foo`, matching a worker deployed on the route `example.com/*`, only showed the logs from requests to `example.com/foo`, and not requests to `example.com/baz` (which would be handled by the same worker).

So this is actually two issues:

1. If the user passes a URL that is _more specific_ than the matching route (and therefore worker), should we filter logs to only print those that occur at that given URL?
2. Should we implement a filter in the trace worker that allows for filtering of `FetchEvent`s based on the URL they hit?

I think the answer to 1 is no, but the answer to 2 is kind of unclear -- and also outside the scope of this PR. It could be worth seeing if this is a feature people want, and if so we could implement it. But so far, I haven't really seen any requests for this.

Some other thoughts:
- What happens if multiple workers would be triggered on a given route? e.g. a worker is assigned to `example.com/*,` and another worker is assigned to `example.com/api/*`, and the URL given is `example.com/api/v1`?
- Are we making it clear enough exactly what worker and what route we are connecting to? Because we may match a route slightly different from what the user inputs (when we implement the lookup rules as documented in the matching rules section), it should be extremely obvious to the user what exactly they are getting logs from.

2022-08-19 09:12 UTC, penalosa commented
> What happens if multiple workers would be triggered on a given route? e.g. a worker is assigned to example.com/*, and another worker is assigned to example.com/api/*, and the URL given is example.com/api/v1?

I _think_ only one of those workers would run, governed by the precedence rules (which is why we'd need to implement those, so wrangler could figure out that tailing the `example.com/api/*` worker is the right thing to do). 

From https://developers.cloudflare.com/workers/platform/routing/routes/#matching-behavior

> When more than one route pattern could match a request URL, the most specific route pattern wins. For example, the pattern `www.example.com/*` would take precedence over `*.example.com/*` when matching a request for `https://www.example.com/`. The pattern `example.com/hello/*` would take precedence over `example.com/*` when matching a request for `example.com/hello/world`

2022-08-19 12:49 UTC, rozenmd commented on packages/wrangler/src/zones.ts
> + * Given a route which isn't valid, sort the valid routes by closeness (levenstein distance)
total nitpick but:

```suggestion
 * Given an invalid route, sort the valid routes by closeness to the invalid route (levenstein distance)
```

2022-08-22 13:15 UTC, caass approved these changes
Awesome! Looks good to me 👍🏻

2022-08-22 13:19 UTC, merged