Add useful link to dashboard when Queue commands fail due to being un…
cloudflare/wrangler2 pull request #2208
Opened 2022-11-16 20:36 UTC by OilyLime

…authorized

2022-11-16 20:41 UTC, JacobMGEvans approved these changes

2022-11-16 20:42 UTC, JacobMGEvans requested changes
Please add a changeset

2022-11-16 20:45 UTC, OilyLime commented
> Please add a changeset

Done, thanks.

2022-11-16 21:00 UTC, JacobMGEvans approved these changes

2022-11-16 21:01 UTC, JacobMGEvans requested changes
Some test snapshots need to be updated it looks like.
```shell
FAIL src/__tests__/queues.test.ts
  ● wrangler › queues › create › should show link to dash when not enabled

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `wrangler queues create should show link to dash when not enabled 1`

    - Snapshot  - 0
    + Received  + 0

    @@ -7,5 +7,5 @@

        If you think this is a bug, please open an issue at:
        https://github.com/cloudflare/wrangler2/issues/new/choose

      ↵

      178 | 					runWrangler(`queues create ${queueName}`)
      179 | 				).rejects.toThrowError();
    > 180 | 				expect(std.out).toMatchInlineSnapshot(`"Creating queue testQueue.
          | 				                ^
      181 | You do not have Queues enabled on your account. Go to https://dash.staging.cloudflare.com/some-account-id/workers/queues to enable.
      182 |
      183 | X [ERROR] A request to the Cloudflare API (/accounts/some-account-id/workers/queues) failed.

      at Object.<anonymous> (src/__tests__/queues.test.ts:180:21)
```

2022-11-16 21:11 UTC, OilyLime commented
@JacobMGEvans Here I was, editing the snapshots by hand...

2022-11-16 21:32 UTC, JacobMGEvans approved these changes

2022-11-18 16:50 UTC, elithrar commented on packages/wrangler/src/queues/utils.ts
> +				`You do not have Queues enabled on your account. Go to https://dash.staging.cloudflare.com/${accountId}/workers/queues to enable.`
```suggestion
				`Queues is not currently enabled on this account. Go to https://dash.cloudflare.com/${accountId}/workers/queues to enable it.`
```

2022-11-21 10:32 UTC, rozenmd approved these changes
FYI for future PRs: https://github.com/cloudflare/wrangler2/pull/2205

2022-11-21 10:32 UTC, rozenmd commented on .changeset/fast-dryers-unite.md
> +"wrangler": minor
```suggestion
"wrangler": patch
```

2022-11-21 10:58 UTC, rozenmd commented
@OilyLime / @elithrar merge when ready

2022-11-21 16:24 UTC, merged