quick win fix: fix test flakiness with experimentalDisableDevRegistry
cloudflare/wrangler2 pull request #2342
Opened 2022-12-06 14:58 UTC by rozenmd

2022-12-06 15:07 UTC, JacobMGEvans approved these changes

2022-12-09 17:05 UTC, penalosa requested changes
I wonder if this might be a good opportunity to destructure things less? Most of the changeset of this PR comes from destructuring `apiOptions`, and I wonder if keeping it as `apiOptions` throughout would be cleaner, and allow for simpler adding of new options

2022-12-09 17:05 UTC, penalosa commented on packages/wrangler/src/api/dev.ts
> +	} = apiOptions || {};
```suggestion
	} = apiOptions ?? {};
```

2022-12-09 19:45 UTC, JacobMGEvans commented on packages/wrangler/package.json
> +		"test": "npm run assert-git-version && cross-env NODE_OPTIONS=--max_old_space_size=8192 jest --silent=false --verbose=true",
Boosting the memory in tests for then removing `--runInBand` which causes the tests to run concurrently. So the change would give Jest more memory to run tests in parallel.

2022-12-13 09:39 UTC, rozenmd commented on packages/wrangler/src/__tests__/api-devregistry.test.js
> +jest.unmock("undici");
This test shouldn't use any mocking - I want an actual HTTP server running, and I want to actually fetch from it

2022-12-13 09:40 UTC, rozenmd commented on fixtures/local-mode-tests/tests/headers.test.ts
> +			{ disableExperimentalWarning: true, experimentalDisableDevRegistry: true }
Yes - DevRegistry should be enabled in `unstable_dev` when testing multi-worker configurations, such as https://developers.cloudflare.com/workers/wrangler/api/#multi-worker-example

2022-12-13 18:16 UTC, penalosa commented
@rozenmd Passing it down through the call stack as `apiOptions`, and using it as `apiOptions. experimentalDisableDevRegistry` when an option is needed.

2022-12-19 07:46 UTC, rozenmd commented
@penalosa can you share an example of what you mean?

To me that sounds like it would save like ~3 LOC in https://github.com/cloudflare/wrangler2/pull/2342/files#diff-3cfa6108cd2ddf7c511b1d3dc125143eb1a56aea1f1807bfc9a8e8c6aba5f45fR84-R88 - most of the changes in the PR are tests

2022-12-20 15:51 UTC, penalosa commented
Just don't want to end up in the same situation of the regular dev with loads of options being re-passed down in every function. Not a big deal here though, I was more concerned with the `unmock` of `undici`, but it sounds like that's okay. Approving pending Windows tests passing

2022-12-20 15:51 UTC, penalosa approved these changes

2022-12-27 11:23 UTC, rozenmd commented
Closing this PR in favour of another that uses `disableDevRegistry` inside the new `experimental` object

2022-12-27 11:23 UTC, closed without merging