Allow `--experimental-local` to cleanly exit on `x`/`CTRL-C`
cloudflare/wrangler2 pull request #2400
Opened 2022-12-13 12:29 UTC by mrbbot

#### What this PR solves / how to test:

In the bootstrapper script `bin/wrangler.js`, we open an IPC channel, so IPC messages from the Wrangler process are propagated through the bootstrapper. Normally, Node's SIGINT handler would close this for us, but interactive mode enables raw mode on stdin which disables the built-in handler. This PR calls `process.disconnect()` to close this channel when we press `x` or CTRL-C, ensuring no open handles, and allowing for a clean exit.

This PR can be tested by running `wrangler dev --experimental-local` on a simple Worker script, then pressing, `x`, `q` and/or `CTRL-C`.

#### Associated docs issues/PR:

N/A

#### Author has included the following, where applicable:

- [ ] ~~Tests~~ (will make sure this is tested as part of https://github.com/cloudflare/wrangler2/pull/2365)
- [x] Changeset

#### Reviewer has performed the following, where applicable:

- [ ] Checked for inclusion of relevant tests
- [ ] Checked for inclusion of a relevant changeset
- [ ] Checked for creation of associated docs updates
- [ ] Manually pulled down the changes and spot-tested

Fixes #2387

2022-12-13 12:48 UTC, petebacondarwin approved these changes
Accepting that a proper test for this will be added in #2365 - LGTM.
Nice comments.

2022-12-13 12:51 UTC, petebacondarwin requested changes
Hmm... actually, I just tried the preview build of this:

```sh
pwd
> wrangler2/fixtures/worker-app
npx https://prerelease-registry.devprod.cloudflare.dev/runs/3685399221/npm-package-wrangler-2400 dev --experimental-local
```

And I still had to add the extra Ctrl-C after pressing Q.

2022-12-13 18:08 UTC, penalosa approved these changes
LGTM! Is this a concern for `unstable_dev`?

2022-12-15 13:52 UTC, penalosa approved these changes

2022-12-15 14:03 UTC, merged