Fix silent failure when browser open doesn't work
cloudflare/wrangler2 pull request #263
Opened 2022-01-18 21:20 UTC by jkriss

The solution in #211 doesn't work, because the error is thrown by the child process returned by the `open` function, not by the `open` itself.

Tested with GitHub Codespaces.

2022-01-18 21:35 UTC, petebacondarwin approved these changes
LGTM.

2022-01-18 21:46 UTC, threepointone requested changes
This is looking good! Please add a changeset, as per the instructions. Also, run `npm run prettify` at the root of the package to pass the build error.

2022-01-18 22:58 UTC, threepointone approved these changes
This looks good, thank you very much for your PR!

2022-01-18 22:58 UTC, merged

2022-01-18 23:00 UTC, threepointone commented
You can try the fix by using `wrangler@alpha`. We'll eventually do a beta release, probably early next week.

2022-01-18 23:24 UTC, jkriss commented
Nice, my fix works with `wrangler@alpha`. I did, however, get this error with alpha:

`Cannot find package '@miniflare/core' imported from /workspaces/finite.photos/node_modules/wrangler/wrangler-dist/cli.js` Running `npm i -D @miniflare/core` fixed it.

Looks like that came in with #186 , but the `@miniflare/core` package wasn't added to package.json.

2022-01-18 23:44 UTC, threepointone commented
Thanks for the catch! This might be because of https://github.com/cloudflare/wrangler2/pull/264. I'll fix this tomorrow.

2022-01-19 07:02 UTC, petebacondarwin commented
`miniflare/core` is a dependency of `miniflare`, so it should not need to be directly added to the wrangler `package.json` nor your own project. I just updated a project to wrangler@alpha and all these deps were there. I wonder if your node_modules just got a bit corrupted when you updated to alpha?