Add `wrangler2` as an alias
cloudflare/wrangler2 pull request #40
Opened 2021-11-23 02:53 UTC by TehShrike

So that when wrangler2 is installed along @cloudflare/wrangler, they can each be referenced in dev scripts.

2021-11-23 02:59 UTC, TehShrike commented
My current workaround is to publish a fork https://www.npmjs.com/package/@tehshrike/wrangler2

2021-11-23 09:02 UTC, GregBrimble commented
Pretty sure can reference wrangler v1 with `npx @cloudflare/wrangler`, so you should be able to avoid this conflict already.

2021-11-23 09:22 UTC, threepointone commented
This PR seems unnecessary. You can install wrangler locally to a project and refer to it via npm scripts, or use npx.

2021-11-23 09:23 UTC, threepointone requested changes
As mentioned

2021-11-25 02:53 UTC, TehShrike commented
> Pretty sure can reference wrangler v1 with `npx @cloudflare/wrangler`, so you should be able to avoid this conflict already.

Nope, I tried that – `npx` looks up `@cloudflare/wrangler`, checks to see what its `bin` script name is, looks in `node_modules/.bin`, sees that `wrangler` exists there, and calls it.

> This PR seems unnecessary. You can install wrangler locally to a project and refer to it via npm scripts, or use npx.

There is currently no way to install both `wrangler` and `@cloudflare/wrangler` and reliably execute one or the other via `npm run` scripts.

I was not using any global scripts, I was only using versions of wrangler that were direct dependencies of my project.

2021-11-25 09:50 UTC, threepointone commented
Noted, thanks for the investigation. Lemme think about this, but I'm leaning towards merging this atm.

2021-11-29 09:49 UTC, threepointone approved these changes

2021-11-29 09:49 UTC, merged