fix: don't crash when browser windows don't open
cloudflare/wrangler2 pull request #415
Opened 2022-02-08 11:59 UTC by threepointone

We open browser windows for a few things; during `wrangler dev`, and logging in. There are environments where this doesn't work as expected (like codespaces, stackblitz, etc). This fix simply logs an error instead of breaking the flow. This is the same fix as https://github.com/cloudflare/wrangler2/pull/263, now applied to the rest of wrangler.

2022-02-08 15:06 UTC, petebacondarwin requested changes
Could we just move this into a helper function? It would help keep the call-sites cleaner and would also encourage others to do the right thing when they need to open a thingy.
It also would help, later, when writing tests, since it would be easier to mock out.

2022-02-09 11:32 UTC, threepointone commented
Sorry if I'm missing something, but I don't think this is related to sentry? Do we suppose we'll want to capture failures to open these windows? I'd think not. It usually means that they're using wrangler inside something like codespaces, where the failure is expected, we just don't want the process to crash.

2022-02-09 12:07 UTC, threepointone commented on packages/wrangler/src/pages.tsx
> +            await openInBrowser(`http://localhost:${port}/`);
@GregBrimble ^ I also replaced pages' usage of `open()`, fyi.

2022-02-09 12:09 UTC, petebacondarwin approved these changes

2022-02-09 12:11 UTC, merged

2022-02-09 13:25 UTC, threepointone commented
lol dammit, thanks @mrbbot