add --watch arg to pages dev
cloudflare/wrangler2 pull request #71
Opened 2021-12-04 14:58 UTC by rkusa

This PR adds the `--watch` arg to `wrangler pages dev`, which allows including other build directories into the watch list of miniflare.

There are use-cases where a pages function imports the result of another build. In my case, it's the build of an Remix app. Reduced for the sake of simplicity, my function looks like:

```ts
import { handleRequest } from "../worker/remix";
export async function onRequest({ request }: EventContext<Env, string, unknown>) {
  return handleRequest(request);
}
```

Changes to my remix app are not reflected when running `wrangler pages dev`. This is because it doesn't watch for changes of `../worker` in my case.

This is why I agree with #49, that it would be very useful to be able to pass one or multiple `--watch` args to `wranger pages dev`. With the PR, I can run wrangler via `wrangler pages dev public --watch ./worker` and now get updates when I change my remix app.

Fixes #49

2021-12-04 15:28 UTC, threepointone requested changes
Thanks for the PR! Marking as changes requested until I can have a look at this next week.

2021-12-18 14:41 UTC, GregBrimble commented
Thank you for your contribution! We've proof-of-concepted a solution which automatically picks up dependent directories, so I think we'll try get that in instead as we open-source the functions compiler itself.

I'll leave this open in case that doesn't work, but hopefully we'll have something up shortly.

2021-12-20 19:37 UTC, joostmeijles commented
Any expectations on an ETA to have this in? (this is blocking me from doing Remix development using Cloudflare workers, see also https://github.com/remix-run/remix/issues/1137)

2021-12-30 08:23 UTC, rkusa commented
> We've proof-of-concepted a solution which automatically picks up dependent directories, so I think we'll try get that in instead as we open-source the functions compiler itself.

This change is available in `wrangler@pages` according to a message on Discord. I've tried it and it works fine, so I think this can be closed now. Not having to manually specify what to watch is an even better solution, I am glad it was possible 👍

2021-12-30 08:23 UTC, closed without merging

2022-03-01 11:57 UTC, motiejunas commented
> > We've proof-of-concepted a solution which automatically picks up dependent directories, so I think we'll try get that in instead as we open-source the functions compiler itself.
> 
> This change is available in `wrangler@pages` according to a message on Discord. I've tried it and it works fine, so I think this can be closed now. Not having to manually specify what to watch is an even better solution, I am glad it was possible 👍

When this will be merged to `main`? Can't wait.

2022-03-02 10:17 UTC, GregBrimble commented
It should be available in `wrangler@beta` and `wrangler@alpha` already! Please file an issue if you're not seeing us automatically pick up changes.

2022-03-02 10:25 UTC, motiejunas commented
> It should be available in `wrangler@beta` and `wrangler@alpha` already! Please file an issue if you're not seeing us automatically pick up changes.

I am using `watch` flag this way:
`wrangler pages dev --watch --proxy 3000 -- npm start`

However, this does not have any effect. What is the correct usage?

2022-03-03 12:00 UTC, GregBrimble commented
You shouldn't need the `--watch` flag. We automatically watch all dependents, always. Can you make an issue with repro steps, please?