chore: setup the workflows to cache
cloudflare/wrangler2 pull request #977
Opened 2022-05-12 16:31 UTC by JacobMGEvans

Added caching of `node_modules` which will skip `npm ci` when nothing has changed in any `package.json`
also using the `setup-node` built-in cache of `~/.npm` which will speed up `npm ci` when it has to run.

2022-05-13 10:18 UTC, petebacondarwin commented
I tried re-running the jobs to check the caching. It looks like the Windows jobs failed.
I think this is because the sub-package `node_modules` folders are not being cached properly?

2022-05-13 10:18 UTC, petebacondarwin requested changes
Windows jobs are failing on second run (checking the cache)

2022-05-13 16:38 UTC, JacobMGEvans commented
> Windows jobs are failing on second run (checking the cache)

@petebacondarwin Made an addition and reran it a couple times. Thanks for the initial rerun!

2022-05-15 17:24 UTC, petebacondarwin approved these changes
Love it!

2022-05-15 18:33 UTC, merged

2022-05-16 07:29 UTC, threepointone commented
Something here is breaking my PR on windows 🙃 https://github.com/cloudflare/wrangler2/runs/6447784315?check_suite_focus=true

2022-05-16 07:33 UTC, threepointone commented
`npm install` sets up workspace symbolic links, does `npm ci` do that as well?

2022-05-16 08:38 UTC, petebacondarwin commented
Yep.